### ISSUE TITLE
NSchemer gets into an endless loop

### ISSUE THREAD

**Issue by gerrod** [Rophuine/NSchemer#2]
To reproduce:
- Upgrade a database to Version 2
- Add an upgrade script for Version 1
- Try to run NSchemer

NSchemer tries to be clever (by ignoring the version 1 script since its lower than Version 2):

```
// From: SqlClientDatabase.Update()
foreach (ITransition v in Versions)
{
    if (!AllVersions.Contains(v.VersionNumber) && v.VersionNumber < DatabaseVersion)
        missingUpdates.Add(v);
}
```

However, the `IsCurrent()` check reports `false` since the Version 1 script hasn't been applied. So, the loop:

```
while (!IsCurrent() && appliedUpdate)
```

Never exits, since `appliedUpdate` never gets changed.

**Comment by Rophuine** [comment]
All of the updates before the latest version should be run by a different piece of code, higher up that method:

```
        foreach (ITransition v in missingUpdates)
            RunUpdate(v);
```

That isn't checking return values, so it's possible that one of those might fail, but the update process will continue (which it shouldn't once one has failed). This would cause that endless loop.

**Comment by gerrod** [comment]
Yes, but the lower version number never gets into the `missingUpdates` list:

```
foreach (ITransition v in Versions)
{
    // NOTE CHECK HERE:
    //     v.VersionNumber < DatabaseVersion
    // SINCE 1 < 2, THE VERSION 1 SCRIPT WON'T GO INTO missingUpdates
    if (!AllVersions.Contains(v.VersionNumber) && v.VersionNumber < DatabaseVersion)
        missingUpdates.Add(v);
}
```

**Comment by Rophuine** [comment]
A wrote a unit test which starts out with only version 2, calls update, then adds v1 and calls update again. UpdateTests.vs, MissingUpdatesShouldBeRun(). Debugging into the second Update() call:
![image](https://cloud.githubusercontent.com/assets/4100713/8449481/1854f284-2015-11e5-8989-ad77845a5958.png)
So it definitely ends up in the list.

I reproduced the infinite loop with the same situation, but when the v1 updater returns false - WhenAMissingUpdateReturnsFalse_NSchemerShouldNotLoopEndlessly() in the same file.

I still haven't found a way to reproduce if the updater succeeds.

**Comment by gerrod** [comment]
Hmmm, is the code on GitHub up to date? Logically I can't see how a smaller
number would get into the missing list since it explicitly ignores versions
smaller than the current version (in the code snippet I sent through). I'll
try to reproduce it tomorrow in a unit test.

**Comment by Rophuine** [comment]
I think you're misreading the logic - if v.VersionNumber < DatabaseVersion, then add it to the list. So in this example, if 1 < 2 (which it is), the version will be added to the list.

**Comment by gerrod** [comment]
Ha! You're right; egg on my face. Doesn't explain our endless loop though, unless (as you pointed out) the updater is failing for some reason. I haven't seen what the updaters are doing (I didn't write them!) but will look into that tomorrow - thanks.

**Comment by Rophuine** [comment]
If you update NSchemer it should now throw an exception telling which update failed, if that's the problem.

**Comment by gerrod** [comment]
Awesome, thanks. I'll let you know if that solves the issue.

**Comment by gerrod** [comment]
Hi @Rophuine, looks like that last update solved the problem, thanks.

**Comment by Rophuine** [comment]
No problem! Hope everything is going well over there.
