### ISSUE TITLE
Default assembly for SqlScriptTransition doesn't make sense

### ISSUE THREAD

**Issue by gerrod** [Rophuine/NSchemer#3]
SqlScriptTransition provides a constructor that does not require an assembly to be passed. This constructor overloads the constructor that _does_ require an assembly, by passing `null` as the `sourceAssembly` argument:

```
public SqlScriptTransition(double versionNumber, string name, string description, string embeddedResourceName) 
    : this(versionNumber, name, description, null, embeddedResourceName) { }

public SqlScriptTransition(double versionNumber, string name, string description, Assembly sourceAssembly,
    string embeddedResourceName)
{
    SourceAssembly = sourceAssembly ?? GetType().Assembly;
    EmbeddedResourceName = embeddedResourceName;
    Description = description;
    Name = name;
    VersionNumber = versionNumber;
}
```

The default assembly used in this case then resolves to the `NSchemer` assembly. This is a nonsensical scenario though - it would be difficult to embed a resource into the `NSchemer` assembly.

Perhaps a more sensible approach would be to:
- Throw an exception if `sourceAssembly` is passed as `null`; and
- Either remove the constructor which does not have the `sourceAssembly` parameter, or provide `Assembly.GetCallingAssembly()` as the default for `sourceAssembly`.

**Comment by Rophuine** [comment]
Agreed. I'll get a fix in. I do want to support this option to keep code in the configuration class shorter.

**Comment by gerrod** [comment]
:+1:

**Comment by Rophuine** [comment]
Fix should be on nuget shortly.

**Comment by Rophuine** [comment]
I just uploaded a second build fixing the same issue if the caller passes in null for some reason, instead of omitting the parameter.
